---
title: "CellChat_Analysis"
author: "Gayani GImhani Anandagoda"
date: '`r Sys.Date()`'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(CellChat)
library(patchwork)
options(stringsAsFactors = FALSE)
```


```{r}
expr_deseq2_norm_log = readRDS("C:/Users/Sahas/Downloads/Masters_Thesis/Ligand-receptor/CellChat/deconvoluted_data/geomx_qc_norm_batch_eff_rm_deconvoluted_deseq2_norm_log.RDS")
```

```{r}
metadt_all = readRDS("C:/Users/Sahas/Downloads/Masters_Thesis/Ligand-receptor/CellChat/deconvoluted_data/metadt_all.RDS")
```


```{r meta data}

meta = data.frame(samples = metadt_all$Sample, NACT_status = metadt_all$NACT_status, Patient = metadt_all$Patient, row.names = rownames(metadt_all))

cell_types <- sapply(strsplit(rownames(metadt_all), "_"), function(x) x[2])
meta = data.frame(labels = cell_types, meta)

meta$samples <- as.factor(meta$samples)

meta$labels <- as.factor(meta$labels)

```


```{r create cell chat obj}
cellchat_obj = createCellChat(object = expr_deseq2_norm_log , meta = meta, group.by = "labels")
```


```{r filtering}

# this has to be done to the CellChat object
# filtering the genes with variance greater than row_variance_cutoff  

Tcells_mat <- expr_deseq2_norm_log[, grep("tumor", colnames(expr_deseq2_norm_log)), drop = FALSE]
row_variance_cutoff = 0.01

row_variance <- apply(Tcells_mat, 1, var)

Tcells_mat_filtered <- Tcells_mat[row_variance >= row_variance_cutoff, , drop = FALSE]


dim(Tcells_mat_filtered)
```

```{r}
library(CellChat)

# Extract the expression matrix from the CellChat object
expr_matrix <- cellchat_obj@data # Ensure this is the correct slot

# Compute variance for each gene
gene_variances <- apply(expr_matrix, 1, var)

# Filter genes that have variance >= 0.01
filtered_genes <- names(gene_variances[gene_variances >= 0.01])

# Subset the CellChat object to retain only filtered genes
cellchat_obj@data <- expr_matrix[filtered_genes, ]

# Check the number of remaining genes
length(filtered_genes)

```

```{r}
library(CellChat)

# Extract metadata containing cell type information
cell_metadata <- cellchat_obj@meta  # Ensure this contains cell type info
cell_types <- unique(cell_metadata$labels)  # Adjust column name if needed

# Initialize a list to store gene variances for each cell type
gene_variances_list <- list()

# Compute variance for each gene in each cell type
for (cell in cell_types) {
  # Get indices of cells belonging to this cell type
  cell_indices <- which(cell_metadata$labels == cell)
  
  # Extract expression matrix for this cell type
  expr_matrix_subset <- cellchat_obj@data[, cell_indices]
  
  # Compute variance for each gene
  gene_variances_list[[cell]] <- apply(expr_matrix_subset, 1, var)
}

# Convert the list to a data frame for easier manipulation
gene_variance_df <- as.data.frame(do.call(cbind, gene_variances_list))

# Keep genes that have variance >= 0.01 in at least one cell type
filtered_genes <- rownames(gene_variance_df)[apply(gene_variance_df, 1, function(x) any(x >= 0.01))]

# Subset the CellChat object to retain only selected genes
cellchat_obj@data <- cellchat_obj@data[filtered_genes, ]

# Check the number of remaining genes
length(filtered_genes)

```

```{r}
apply(gene_variance_df, 2, function(x) sum(x >= 0.01, na.rm = TRUE))

```


# CellChat database

```{r}
CellChatDB <- CellChatDB.human # use CellChatDB.mouse if running on mouse data
#showDatabaseCategory(CellChatDB)

```

```{r}
# use all CellChatDB except for "Non-protein Signaling" for cell-cell communication analysis
CellChatDB.use <- subsetDB(CellChatDB)
```

```{r}
# set the used database in the object
cellchat_obj@DB <- CellChatDB.use
```

# Preprocessing the expression data for cell-cell communication analysis

```{r}
cellchat_obj <- subsetData(cellchat_obj) # This step is necessary even if using the whole database
future::plan("multisession", workers = 4) # do parallel
cellchat_obj <- identifyOverExpressedGenes(cellchat_obj)
cellchat_obj <- identifyOverExpressedInteractions(cellchat_obj)

# execution.time = Sys.time() - ptm
#print(as.numeric(execution.time, units = "secs"))



```

```{r}
# check !!!!

# project gene expression data onto PPI (Optional: when running it, USER should set `raw.use = FALSE` in the function `computeCommunProb()` in order to use the projected data)
# cellchat <- projectData(cellchat, PPI.human)

```


# Part II: Inference of cell-cell communication network

```{r}

ptm = Sys.time()
cellchat_obj <- computeCommunProb(cellchat_obj, type = "triMean")



#triMean is used for calculating the average gene expression per cell group. 
#[1] ">>> Run CellChat on sc/snRNA-seq data <<< [2025-03-21 20:03:14.963692]"
#  |====================================================| 100%
#[1] ">>> CellChat inference is done. Parameter values are stored in `object@options$parameter` <<< [2025-03-21 22:37:24.831767]"

# run time : aprox: 2.5 hrs
```

```{r}
saveRDS(cellchat_obj , file = "C:/Users/Sahas/Downloads/Masters_Thesis/Ligand-receptor/CellChat/deconvoluted_data/cellchat_obj.RDS")
```




