---
title: "CellChat_Visualization"
author: "Gayani GImhani Anandagoda"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(CellChat)
library(patchwork)
options(stringsAsFactors = FALSE)
```

```{r}
cellchat = readRDS( "C:/Users/Sahas/Downloads/Masters_Thesis/Ligand-receptor/CellChat/deconvoluted_data/cellchat_obj.RDS")
```

```{r}
cellchat <- computeCommunProbPathway(cellchat)
```

```{r}
cellchat = filterCommunication(cellchat, min.cells = 10)
```

```{r}
cells.level = levels(cellchat@idents)
cells.level
cells.level[c(1,2)]
```


```{r}
df.net <- subsetCommunication(cellchat, slot.name = "netP") 

#returns a data frame consisting of all the inferred cell-cell communications at the level of ligands/receptors. Set slot.name = "netP" to access the the inferred communications at the level of signaling pathways

#df.net <- subsetCommunication(cellchat, sources.use = c(1,5), targets.use = c(8,9))
df.net <- subsetCommunication(cellchat, sources.use = 9, targets.use = 8)
#gives the inferred cell-cell communications sending from cell groups 1 and 2 to cell groups 4 and 5.

df.net <- subsetCommunication(cellchat, signaling = c("IL12", "IL4" , "IL6")) 
#gives the inferred cell-cell communications mediated by signaling WNT and TGFb.
```

```{r}
cellchat <- aggregateNet(cellchat)
```

```{r}

groupSize <- as.numeric(table(cellchat_aggregateNet@idents))
par(mfrow = c(1,2), xpd=TRUE)
netVisual_circle(cellchat_aggregateNet@net$count, vertex.weight = groupSize, weight.scale = T, label.edge= F, title.name = "Number of interactions")

netVisual_circle(cellchat_aggregateNet@net$weight, vertex.weight = groupSize, weight.scale = T, label.edge= F, title.name = "Interaction weights/strength")
```


```{r}
mat <- cellchat_aggregateNet@net$weight
par(mfrow = c(3,4), xpd=TRUE)
for (i in 1:nrow(mat)) {
  mat2 <- matrix(0, nrow = nrow(mat), ncol = ncol(mat), dimnames = dimnames(mat))
  mat2[i, ] <- mat[i, ]
  netVisual_circle(mat2, vertex.weight = groupSize, weight.scale = T, edge.weight.max = max(mat), title.name = rownames(mat)[i])
}
```

```{r}
mat2 <- matrix(0, nrow = nrow(mat), ncol = ncol(mat), dimnames = dimnames(mat))
mat2[5, ] <- mat[5, ]
netVisual_circle(mat2, vertex.weight = groupSize, weight.scale = T, edge.weight.max = max(mat), title.name = rownames(mat)[5])
```


```{r}
pathways.show <- c("IL12") 
```

```{r}
netVisual_heatmap(cellchat, signaling = pathways.show, color.heatmap = "Reds")
```
```{r}
netAnalysis_contribution(cellchat_aggregateNet, signaling = pathways.show)
```

```{r}
# Compute the network centrality scores
cellchat <- netAnalysis_computeCentrality(cellchat, slot.name = "netP") # the slot 'netP' means the inferred intercellular communication network of signaling pathways
# Visualize the computed centrality scores using heatmap, allowing ready identification of major signaling roles of cell groups
netAnalysis_signalingRole_network(cellchat, signaling = pathways.show, width = 8, height = 2.5, font.size = 10)
```

```{r}
plotGeneExpression(cellchat_aggregateNet, signaling = "IL12", enriched.only = TRUE)
```

```{r}
# (1) show all the significant interactions (L-R pairs) from some cell groups (defined by 'sources.use') to other cell groups (defined by 'targets.use')
netVisual_bubble(cellchat, sources.use = 4, targets.use = 5, remove.isolate = FALSE)
#> Comparing communications on a single object
```

```{r}

```

