---
title: "MultiNichnetr for Geomx"
author: "Gayani GImhani Anandagoda"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages, message=FALSE}
library(Seurat)
library(SeuratObject)
library(SingleCellExperiment)
library(dplyr)
library(ggplot2)

library(nichenetr)
library(multinichenetr)


library("ggplot2")
library(gridExtra)


library(tidyverse)
library(DESeq2)

```


```{r}

organism = "human"

cell_types = c("Tcells","Macrophages") 

cell_frac_cutoff = NULL

celltype_id = "labels" 

cell_idents = c("Tcells","Macrophages")

sample_id = "new_sample_id"

group_id = "NACT_Segment"

min_cells = 4

batches = NA

covariates =  NA # "samples" 

min_sample_prop = 0.50 

fraction_cutoff = 0.05

input_dir = "C:/Users/Sahas/Downloads/Masters_Thesis/Data/Batch01/"

#bprism_res = readRDS(paste0(input_dir,"bp_res_mid_lvl_ct.RDS"))

#geomx_obj = readRDS(paste0(input_dir,"geomx_qc_norm_batch_eff_rm.RDS"))

```

```{r}

# Set contrasts
contrasts_oi <- c("'pre_tumor-pre_stroma','pre_stroma-pre_tumor'")

# Create a contrast table
contrast_tbl <- tibble(contrast = c("pre_tumor-pre_stroma","pre_stroma-pre_tumor"), 
                       group = c("pre_tumor", "pre_stroma"))  
```


```{r Extracting expression data and normalization and filtering based on cell frcation}
# Extracting expression data of the desired cell types and saving it as a r object

if (is.null(cell_types)) { # If the cell types are not defined take all the cell types in the prism object
  ct_names <- colnames(bprism_res@posterior.theta_f@theta.cv)

}else{
  ct_names <- cell_types
}



deconv_ct_list <- setNames(lapply(ct_names, function(ct_name) {
  cell_frac_cv <- as.data.frame(bprism_res@posterior.theta_f@theta.cv)
  
  # Mask cell fractions if CV > 0.2
  cell_to_rm <- rownames(cell_frac_cv)[cell_frac_cv[[ct_name]] > 0.2]
  
  deconv_ct <- BayesPrism::get.exp(bp = bprism_res,
                                   state.or.type = "type",
                                   cell.name = ct_name)
  
  # Filter out cells with high CV
  deconv_ct <- deconv_ct[!(rownames(deconv_ct) %in% cell_to_rm), ]
  
  
  # filtering based on cell fraction 
  
  if(!is.null(cell_frac_cutoff)){
    
    formatted_ct_names <- gsub(" ", ".", ct_name) #because the cell fraction dataframe colnames are different: dot instead of space
    
    cells_greater_than_cutoff <- cell_fractions_df[cell_fractions_df[, formatted_ct_names] >= cell_frac_cutoff,]$dcc_filename
    
    deconv_ct <- deconv_ct[(colnames(deconv_ct) %in% cells_greater_than_cutoff), ]
    
  }
  
  
  return(deconv_ct)
}), ct_names)  

deconv_ct_list = readRDS("C:/Users/Sahas/Downloads/Masters_Thesis/Ligand-receptor/MultiNichnetR/stromaVstumor/deconv_ct_list.RDS")
```


```{r combine expression data}

deconv_ct_list_int <- lapply(names(deconv_ct_list), function(ct_name){
  mat <- deconv_ct_list[[ct_name]]
  rownames(mat) <- gsub('\\.dcc', paste0('_', ct_name), rownames(mat))
  mat <- apply(mat, c(1, 2), function(x) {(as.integer(x))})
  return(mat)
})

names(deconv_ct_list_int) <- names(deconv_ct_list)

deconv_ct_list_combined <- do.call(rbind, deconv_ct_list_int)

deconv_ct_list_combined = t(deconv_ct_list_combined)

deconv_ct_list_combined = readRDS("C:/Users/Sahas/Downloads/Masters_Thesis/Ligand-receptor/MultiNichnetR/stromaVstumor/deconv_ct_list_combined.RDS")

```

```{r}

deconv_metadt_list <- lapply(names(deconv_ct_list_int), function(ct_name){
  meta_data = sData(geomx_obj)
  
   new_meta <- data.frame(meta_data[,c(2,5,6,7,24,25,28)])
  
  new_meta$dcc_filename = gsub('\\.dcc', paste0('_', ct_name), new_meta$dcc_filename)
  mat = deconv_ct_list_int[[ct_name]]
  
  matched_entries = new_meta[new_meta$dcc_filename %in% rownames(mat), ]
  rownames(matched_entries) = matched_entries$dcc_filename  
  
  return(matched_entries)
})

metadt_all <- do.call(rbind, deconv_metadt_list)

metadt_all = readRDS("C:/Users/Sahas/Downloads/Masters_Thesis/Ligand-receptor/MultiNichnetR/stromaVstumor/metadt_all.RDS")

meta = data.frame(samples = metadt_all$Sample, NACT_status = metadt_all$NACT_status, Patient = metadt_all$Patient, Segment = metadt_all$Segment , Annotation = metadt_all$Annotation_cell, row.names = rownames(metadt_all))

meta = data.frame(meta , NACT_Segment = paste0(meta$NACT_status,'_',meta$Segment))

#meta = meta %>% filter(NACT_status == "post") 

cell_types <- sapply(strsplit(rownames(meta), "_"), function(x) x[2])

meta = data.frame(labels = cell_types, meta)

meta$samples <- as.factor(meta$samples)

meta$labels <- as.factor(meta$labels)

meta_filter = rownames(meta) %in% colnames(deconv_ct_list_combined)

meta = meta[meta_filter,]

meta = data.frame(meta, new_sample_id = paste0(meta$samples,"_",meta$Segment)) # have to change this depending on the group


deconv_ct_list_combined_filter = colnames(deconv_ct_list_combined) %in% rownames(meta)

deconv_ct_list_combined = deconv_ct_list_combined[,deconv_ct_list_combined_filter]

#meta = data.frame(meta, covariate1_samples = meta$samples) # have to change this depending on the group

# meta = readRDS("C:/Users/Sahas/Downloads/Masters_Thesis/Ligand-receptor/MultiNichnetR/stromaVstumor/meta.RDS")


```



```{r}
sce <- SingleCellExperiment(
  assays = list(counts = deconv_ct_list_combined),
  colData = meta
)


# make sure that gene symbols used in the expression data are updated
sce = alias_to_symbol_SCE(sce, "human") %>% makenames_SCE()

# Define sender and receiver cell types
senders_oi <- SummarizedExperiment::colData(sce)[, celltype_id] %>% unique() %>% .[.%in% cell_idents]

receivers_oi <- SummarizedExperiment::colData(sce)[, celltype_id] %>% unique() %>% .[.%in% cell_idents]

sce = sce[, SummarizedExperiment::colData(sce)[,celltype_id] %in% 
            c(senders_oi, receivers_oi)
          ]
```

```{r load lr networks}
dir_name = "C:/Users/Sahas/Downloads/Masters_Thesis/Ligand-receptor/NichNet/Nichenet_Model/" # replace with the url at the end

options(timeout = 120)

if(organism == "human"){
  
  lr_network_all = 
    readRDS(url(
      "https://zenodo.org/record/10229222/files/lr_network_human_allInfo_30112033.rds"
      )) %>% 
    mutate(
      ligand = convert_alias_to_symbols(ligand, organism = organism), 
      receptor = convert_alias_to_symbols(receptor, organism = organism))
  
  lr_network_all = lr_network_all  %>% 
    mutate(ligand = make.names(ligand), receptor = make.names(receptor)) 
  
  lr_network = lr_network_all %>% 
    distinct(ligand, receptor)
  
  ligand_target_matrix = readRDS(paste0(dir_name,"ligand_target_matrix_nsga2r_final.rds"))
  
  colnames(ligand_target_matrix) = colnames(ligand_target_matrix) %>% 
    convert_alias_to_symbols(organism = organism) %>% make.names()
  rownames(ligand_target_matrix) = rownames(ligand_target_matrix) %>% 
    convert_alias_to_symbols(organism = organism) %>% make.names()
  
  lr_network = lr_network %>% filter(ligand %in% colnames(ligand_target_matrix))
  ligand_target_matrix = ligand_target_matrix[, lr_network$ligand %>% unique()]
  
} 

```

```{r diagnostic plots}

abundance_expression_info <- get_abundance_info(sce = sce, 
                                                           sample_id = sample_id, 
                                                           group_id = group_id, 
                                                           celltype_id = celltype_id, 
                                                           min_cells = min_cells, 
                                                           senders_oi = senders_oi, 
                                                           receivers_oi = receivers_oi, 
                                                           #lr_network = lr_network, 
                                                           batches = batches)


# diagnostic plots
# To check whether each cell type have enough number of cells in each sample

#file_name_abundance_expression_info = paste0(output_dir,"abundance_expression_info_all_cell_types_",treatment,".RDS") # file name

#saveRDS(abundance_expression_info, file = file_name_abundance_expression_info)

abundance_expression_info$abund_plot_sample
abundance_expression_info$abund_plot_group
abundance_expression_info$abund_barplot
```


```{r  Cell-type filtering}

################################ Analysis ###############################

# Step 01. Cell-type filtering

abundance_df_summarized = abundance_expression_info$abundance_data %>% 
  mutate(keep = as.logical(keep)) %>% 
  group_by(group_id, celltype_id) %>% 
  summarise(samples_present = sum((keep)))

celltypes_absent_one_condition = abundance_df_summarized %>% 
  filter(samples_present == 0) %>% pull(celltype_id) %>% unique() 
# find truly condition-specific cell types by searching for cell types 
# truely absent in at least one condition

celltypes_present_one_condition = abundance_df_summarized %>% 
  filter(samples_present >= 2) %>% pull(celltype_id) %>% unique() 
# require presence in at least 2 samples of one group so 
# it is really present in at least one condition

condition_specific_celltypes = intersect(
  celltypes_absent_one_condition, 
  celltypes_present_one_condition)

total_nr_conditions = SummarizedExperiment::colData(sce)[,group_id] %>% 
  unique() %>% length() 

absent_celltypes = abundance_df_summarized %>% 
  filter(samples_present < 2) %>% 
  group_by(celltype_id) %>% 
  dplyr::count() %>% 
  filter(n == total_nr_conditions) %>% 
  pull(celltype_id)
  
print("condition-specific celltypes:")
## [1] "condition-specific celltypes:"
print(condition_specific_celltypes)
## character(0)
  
print("absent celltypes:")
## [1] "absent celltypes:"
print(absent_celltypes)
## character(0)

# condition-specific cell types can be filtered out if you as a user do not want to run the alternative workflow for condition-specific cell types in the optional step 8 of the core MultiNicheNet analysis. check !!
```



```{r Gene Filtering}

############## Step 02. Gene Filtering ############

frq_list = get_frac_exprs(
  sce = sce, 
  sample_id = sample_id, celltype_id =  celltype_id, group_id = group_id, 
  batches = batches, 
  min_cells = min_cells, 
  fraction_cutoff = fraction_cutoff, 
  min_sample_prop = min_sample_prop)

# Now only keep genes that are expressed by at least one cell type:

genes_oi = frq_list$expressed_df %>% 
  filter(expressed == TRUE) %>% pull(gene) %>% unique() 
sce = sce[genes_oi, ]

```



```{r Pseudobulk expression calculation}

################ Step 03. Pseudobulk expression calculation ####################

abundance_expression_info = process_abundance_expression_info(
  sce = sce, 
  sample_id = sample_id, group_id = group_id, celltype_id = celltype_id, 
  min_cells = min_cells, 
  senders_oi = senders_oi, receivers_oi = receivers_oi, 
  lr_network = lr_network, 
  batches = batches, 
  frq_list = frq_list, 
  abundance_info = abundance_expression_info)


# Normalized pseudobulk expression values per gene/celltype/sample can be inspected by:

#abundance_expression_info$celltype_info$pb_df %>% head()
#abundance_expression_info$celltype_info$pb_df_group %>% head()
#abundance_expression_info$sender_receiver_info$pb_df %>% head()
#abundance_expression_info$sender_receiver_info$pb_df_group %>% head()
```

```{r DE Analysis}

## Step 04. Differential expression (DE) analysis: #####

DE_info = get_DE_info(
  sce = sce, 
  sample_id = sample_id, group_id = group_id, celltype_id = celltype_id, 
  batches = batches, covariates = covariates, 
  contrasts_oi = contrasts_oi, 
  min_cells = min_cells, 
  expressed_df = frq_list$expressed_df)

#DE_info$celltype_de$de_output_tidy %>% head()

empirical_pval = FALSE

if(empirical_pval == TRUE){
  DE_info_emp = get_empirical_pvals(DE_info$celltype_de$de_output_tidy)
  celltype_de = DE_info_emp$de_output_tidy_emp %>% select(-p_val, -p_adj) %>% 
    rename(p_val = p_emp, p_adj = p_adj_emp)
} else {
  celltype_de = DE_info$celltype_de$de_output_tidy
} 


# Combine DE information for ligand-senders and receptors-receivers

sender_receiver_de = multinichenetr::combine_sender_receiver_de(
  sender_de = celltype_de,
  receiver_de = celltype_de,
  senders_oi = senders_oi,
  receivers_oi = receivers_oi,
  lr_network = lr_network
)

#head(sender_receiver_de)

# plot to check the p value distribution
DE_info$hist_pvals

saveRDS(sender_receiver_de, file = "C:/Users/Sahas/Downloads/Masters_Thesis/Ligand-receptor/MultiNichnetR/without_sample_as_covariate/sender_receiver_de.RDS" )
```

```{r Ligand activity prediction}

logFC_threshold = 0.5
p_val_threshold = 0.05
p_val_adj = TRUE 


top_n_target = 250
verbose = TRUE
cores_system = 2

###### Step 05. Ligand activity prediction #####

geneset_assessment = contrast_tbl$contrast %>% 
  lapply(
    process_geneset_data, 
    celltype_de, logFC_threshold, p_val_adj, p_val_threshold
  ) %>% 
  bind_rows() 



# Perform the ligand activity analysis and ligand-target inference
# increase the number of scores to run the code faster

n.cores = min(cores_system, celltype_de$cluster_id %>% unique() %>% length()) 


ligand_activities_targets_DEgenes = suppressMessages(suppressWarnings(
  get_ligand_activities_targets_DEgenes(
    receiver_de = celltype_de,
    receivers_oi = intersect(receivers_oi, celltype_de$cluster_id %>% unique()),
    ligand_target_matrix = ligand_target_matrix,
    logFC_threshold = logFC_threshold,
    p_val_threshold = p_val_threshold,
    p_val_adj = p_val_adj,
    top_n_target = top_n_target,
    verbose = verbose, 
    n.cores = n.cores
  )
))

ligand_activities_targets_DEgenes$ligand_activities %>% head(5)
```

```{r saveRDS}

saveRDS(ligand_activities_targets_DEgenes, file = "C:/Users/Sahas/Downloads/Masters_Thesis/Ligand-receptor/MultiNichnetR/without_sample_as_covariate/ligand_activities_targets_DEgenes.RDS" )
```




```{r Prioritization}
ligand_activity_down = FALSE

##### Step 06. Prioritization: rank cell-cell communication patterns through multi-criteria prioritization
sender_receiver_tbl = sender_receiver_de %>% distinct(sender, receiver)

metadata_combined = SummarizedExperiment::colData(sce) %>% tibble::as_tibble()

if(!is.na(batches)){
  grouping_tbl = metadata_combined[,c(sample_id, group_id, batches)] %>% 
    tibble::as_tibble() %>% distinct()
  colnames(grouping_tbl) = c("sample","group",batches)
} else {
  grouping_tbl = metadata_combined[,c(sample_id, group_id)] %>% 
    tibble::as_tibble() %>% distinct()
  colnames(grouping_tbl) = c("sample","group")
}

prioritization_tables = suppressMessages(multinichenetr::generate_prioritization_tables(
    sender_receiver_info = abundance_expression_info$sender_receiver_info,
    sender_receiver_de = sender_receiver_de,
    ligand_activities_targets_DEgenes = ligand_activities_targets_DEgenes,
    contrast_tbl = contrast_tbl,
    sender_receiver_tbl = sender_receiver_tbl,
    grouping_tbl = grouping_tbl,
    scenario = "regular", # all prioritization criteria will be weighted equally
    fraction_cutoff = fraction_cutoff, 
    abundance_data_receiver = abundance_expression_info$abundance_data_receiver,
    abundance_data_sender = abundance_expression_info$abundance_data_sender,
    ligand_activity_down = ligand_activity_down
  ))

# This table gives the final prioritization score of each interaction, and the values of the individual prioritization criteria.

prioritization_tables$group_prioritization_tbl %>% head(5)
```


```{r save table}
# SAVE THE "prioritization_tables" TABLE AS A R OBJECT

saveRDS(prioritization_tables, file = "C:/Users/Sahas/Downloads/Masters_Thesis/Ligand-receptor/MultiNichnetR/without_sample_as_covariate/post_stromaVspost_tumor/prioritization_tables_all_cell_types.RDS")
```


###################### Visualization ################


### # Create circos plots

```{r circos plots}
prioritized_tbl_oi_all <- get_top_n_lr_pairs(prioritization_tables, 50, rank_per_group = TRUE)

prioritized_tbl_oi <- prioritization_tables$group_prioritization_tbl %>%
  filter(id %in% prioritized_tbl_oi_all$id) %>%
  distinct(id, sender, receiver, ligand, receptor, group) %>% left_join(prioritized_tbl_oi_all)

# Set NA values to zero
prioritized_tbl_oi$prioritization_score[is.na(prioritized_tbl_oi$prioritization_score)] <- 0

# Define sender and receiver cells
senders_receivers <- union(prioritized_tbl_oi$sender %>% unique(), prioritized_tbl_oi$receiver %>% unique()) %>% sort()

# Set colors for sender and receiver cells
colors_sender <- RColorBrewer::brewer.pal(n = length(senders_receivers), name = 'Spectral') %>% magrittr::set_names(senders_receivers)
colors_receiver <- RColorBrewer::brewer.pal(n = length(senders_receivers), name = 'Spectral') %>% magrittr::set_names(senders_receivers)

# Create circos plots to visualize top 50 predictions across all contrasts, senders, and receivers of interest
circos_list <- make_circos_group_comparison(prioritized_tbl_oi, colors_sender, colors_receiver)



pdf(file = "C:/Users/Sahas/Downloads/Masters_Thesis/Ligand-receptor/MultiNichnetR/without_sample_as_covariate/post_stromaVspost_tumor/circos_plot_stroma.pdf", width = 10, height = 10)
circos_list$stroma
dev.off()

pdf(file = "C:/Users/Sahas/Downloads/Masters_Thesis/Ligand-receptor/MultiNichnetR/without_sample_as_covariate/post_stromaVspost_tumor/circos_plot_tumor.pdf", width = 10, height = 10)
circos_list$tumor
dev.off()

pdf(file = "C:/Users/Sahas/Downloads/Masters_Thesis/Ligand-receptor/MultiNichnetR/without_sample_as_covariate/post_stromaVspost_tumor/circos_plot_legend.pdf", width = 10, height = 10)
circos_list$legend
dev.off()
```



########### Generating bubble plots

```{r bubble plots , width = 10, height = 10}
group_oi = "post_tumor"

prioritized_tbl_oi_M_50 = prioritized_tbl_oi_all %>% 
  filter(group == group_oi)

plot_oi = make_sample_lr_prod_activity_plots_Omnipath(
  prioritization_tables, 
  prioritized_tbl_oi_M_50 %>% inner_join(lr_network_all)
  )


pdf(file = "C:/Users/Sahas/Downloads/Masters_Thesis/Ligand-receptor/MultiNichnetR/without_sample_as_covariate/post_stromaVspost_tumor/bubble_plot_tumor.pdf", width = 17, height = 10)
plot_oi
dev.off()



group_oi = "post_stroma"

prioritized_tbl_oi_M_50 = prioritized_tbl_oi_all %>% 
  filter(group == group_oi)

plot_oi = make_sample_lr_prod_activity_plots_Omnipath(
  prioritization_tables, 
  prioritized_tbl_oi_M_50 %>% inner_join(lr_network_all)
  )



pdf(file = "C:/Users/Sahas/Downloads/Masters_Thesis/Ligand-receptor/MultiNichnetR/without_sample_as_covariate/post_stromaVspost_tumor/bubble_plot_stroma.pdf", width = 17, height = 10)
plot_oi
dev.off()
```


```{r}
group_oi = "post_stroma"


prioritized_tbl_oi_M_50 = get_top_n_lr_pairs(
  prioritization_tables, 
  50, 
  groups_oi = group_oi, 
  receivers_oi = "Tcells",
  senders_oi = "Macrophages")

plot_oi = make_sample_lr_prod_activity_plots_Omnipath(
  prioritization_tables, 
  prioritized_tbl_oi_M_50 %>% inner_join(lr_network_all))

pdf(file = "C:/Users/Sahas/Downloads/Masters_Thesis/Ligand-receptor/MultiNichnetR/without_sample_as_covariate/post_stromaVspost_tumor/bubble_plot_stroma_receiver_Tcells.pdf", width = 17, height = 10)
plot_oi
dev.off()




prioritized_tbl_oi_M_50 = get_top_n_lr_pairs(
  prioritization_tables, 
  50, 
  groups_oi = group_oi, 
  receivers_oi = "Macrophages",
  senders_oi = "Tcells")

plot_oi = make_sample_lr_prod_activity_plots_Omnipath(
  prioritization_tables, 
  prioritized_tbl_oi_M_50 %>% inner_join(lr_network_all))
pdf(file = "C:/Users/Sahas/Downloads/Masters_Thesis/Ligand-receptor/MultiNichnetR/without_sample_as_covariate/post_stromaVspost_tumor/bubble_plot_stroma_sender_Tcells.pdf", width = 17, height = 10)
plot_oi
dev.off()

```

