---
title: "test_Multinichenet_prioritization"
author: "Gayani GImhani Anandagoda"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load packages, message=FALSE}
library(Seurat)
library(SeuratObject)
library(SingleCellExperiment)
library(dplyr)
library(ggplot2)

library(nichenetr)
library(multinichenetr)


library("ggplot2")
library(gridExtra)


library(tidyverse)
library(DESeq2)

```

```{r load lr networks}
organism = "human"

dir_name = "C:/Users/Sahas/Downloads/Masters_Thesis/Ligand-receptor/NichNet/Nichenet_Model/" # replace with the url at the end

options(timeout = 120)

if(organism == "human"){
  
  lr_network_all = 
    readRDS(url(
      "https://zenodo.org/record/10229222/files/lr_network_human_allInfo_30112033.rds"
      )) %>% 
    mutate(
      ligand = convert_alias_to_symbols(ligand, organism = organism), 
      receptor = convert_alias_to_symbols(receptor, organism = organism))
  
  lr_network_all = lr_network_all  %>% 
    mutate(ligand = make.names(ligand), receptor = make.names(receptor)) 
  
  lr_network = lr_network_all %>% 
    distinct(ligand, receptor)
  
  ligand_target_matrix = readRDS(paste0(dir_name,"ligand_target_matrix_nsga2r_final.rds"))
  
  colnames(ligand_target_matrix) = colnames(ligand_target_matrix) %>% 
    convert_alias_to_symbols(organism = organism) %>% make.names()
  rownames(ligand_target_matrix) = rownames(ligand_target_matrix) %>% 
    convert_alias_to_symbols(organism = organism) %>% make.names()
  
  lr_network = lr_network %>% filter(ligand %in% colnames(ligand_target_matrix))
  ligand_target_matrix = ligand_target_matrix[, lr_network$ligand %>% unique()]
  
} 

```


```{r}
input_dir = "C:/Users/Sahas/Downloads/Masters_Thesis/Ligand-receptor/MultiNichnetR/stromaVsTumor_run_04/"

output_dir = "C:/Users/Sahas/Downloads/Masters_Thesis/Ligand-receptor/MultiNichnetR/DEGs_calculated_by_Iga_batch1/"
```

```{r}
deconv_ct_list_combined = readRDS(paste0(input_dir,"deconv_ct_list_combined.RDS"))
metadt_all = readRDS(paste0(input_dir,"metadt_all.RDS"))
```

```{r}


meta = data.frame(samples = metadt_all$Sample, NACT_status = metadt_all$NACT_status, Patient = metadt_all$Patient, Segment = metadt_all$Segment , Annotation = metadt_all$Annotation_cell, row.names = rownames(metadt_all))

meta = data.frame(meta , new_sample_ID = paste0(meta$samples,'_',meta$Segment))

cell_types <- sapply(strsplit(rownames(meta), "_"), function(x) x[2])

meta = data.frame(labels = cell_types, meta)

meta$samples <- as.factor(meta$samples)

meta$labels <- as.factor(meta$labels)

meta_filter = rownames(meta) %in% colnames(deconv_ct_list_combined)

meta = meta[meta_filter,]


deconv_ct_list_combined_filter = colnames(deconv_ct_list_combined) %in% rownames(meta)

deconv_ct_list_combined = deconv_ct_list_combined[,deconv_ct_list_combined_filter]

```


```{r}

celltype_id = "labels"
cell_idents = c("Tcells","Macrophages")

sce <- SingleCellExperiment(
  assays = list(counts = deconv_ct_list_combined),
  colData = meta
)


# make sure that gene symbols used in the expression data are updated
sce = alias_to_symbol_SCE(sce, "human") %>% makenames_SCE()

# Define sender and receiver cell types
senders_oi <- SummarizedExperiment::colData(sce)[, celltype_id] %>% unique() %>% .[.%in% cell_idents]

receivers_oi <- SummarizedExperiment::colData(sce)[, celltype_id] %>% unique() %>% .[.%in% cell_idents]

sce = sce[, SummarizedExperiment::colData(sce)[,celltype_id] %in% 
            c(senders_oi, receivers_oi)
          ]


```



```{r}

sample_id = "new_sample_ID"
group_id =  "Segment"
min_cells = 4
batches = NA
min_sample_prop = 0.50
fraction_cutoff = 0.05

abundance_expression_info <- get_abundance_info(sce = sce, 
                                                           sample_id = sample_id, 
                                                           group_id = group_id, 
                                                           celltype_id = celltype_id, 
                                                           min_cells = min_cells, 
                                                           senders_oi = senders_oi, 
                                                           receivers_oi = receivers_oi, 
                                                           batches = batches)


abundance_expression_info$abund_plot_sample
# abundance_expression_info$abund_plot_group
# abundance_expression_info$abund_barplot
# 
# abundance_df_summarized = abundance_expression_info$abundance_data %>% 
#   mutate(keep = as.logical(keep)) %>% 
#   group_by(group_id, celltype_id) %>% 
#   summarise(samples_present = sum((keep)))
# 
# celltypes_absent_one_condition = abundance_df_summarized %>% 
#   filter(samples_present == 0) %>% pull(celltype_id) %>% unique() 


# celltypes_present_one_condition = abundance_df_summarized %>% 
#   filter(samples_present >= 2) %>% pull(celltype_id) %>% unique() 
# 
# 
# condition_specific_celltypes = intersect(
#   celltypes_absent_one_condition, 
#   celltypes_present_one_condition)
# 
# total_nr_conditions = SummarizedExperiment::colData(sce)[,group_id] %>% 
#   unique() %>% length() 
# 
# absent_celltypes = abundance_df_summarized %>% 
#   filter(samples_present < 2) %>% 
#   group_by(celltype_id) %>% 
#   dplyr::count() %>% 
#   filter(n == total_nr_conditions) %>% 
#   pull(celltype_id)


frq_list = get_frac_exprs(
  sce = sce, 
  sample_id = sample_id, celltype_id =  celltype_id, group_id = group_id, 
  batches = batches, 
  min_cells = min_cells, 
  fraction_cutoff = fraction_cutoff, 
  min_sample_prop = min_sample_prop)

# Now only keep genes that are expressed by at least one cell type:

genes_oi = frq_list$expressed_df %>% 
  filter(expressed == TRUE) %>% pull(gene) %>% unique() 
sce = sce[genes_oi, ]


abundance_expression_info = process_abundance_expression_info(
  sce = sce, 
  sample_id = sample_id, group_id = group_id, celltype_id = celltype_id, 
  min_cells = min_cells, 
  senders_oi = senders_oi, receivers_oi = receivers_oi, 
  lr_network = lr_network, 
  batches = batches, 
  frq_list = frq_list, 
  abundance_info = abundance_expression_info)
```


```{r}
DEG_geomx_Mac = read.csv("C:/Users/Sahas/Downloads/Masters_Thesis/Ligand-receptor/MultiNichnetR/DEGs_calculated_by_Iga_batch1/dge_within_slide_Segment_bin_FALSE__/dge_deconv_Macrophages_dge_within_slide_Segment_bin_FALSE__.csv")

celltype_de_edited_mac_1 <- data.frame(
  gene = DEG_geomx_Mac$Gene,
  cluster_id = rep("Macrophages", nrow(DEG_geomx_Mac)),
  logFC = DEG_geomx_Mac$Estimate,
  p_val = DEG_geomx_Mac$Pr...t..,
  p_adj = DEG_geomx_Mac$FDR,
  contrast = rep("stroma-tumor", nrow(DEG_geomx_Mac))
)


celltype_de_edited_mac_2 = celltype_de_edited_mac_1
celltype_de_edited_mac_2$logFC = -celltype_de_edited_mac_2$logFC
celltype_de_edited_mac_2$contrast = gsub("stroma-tumor", "tumor-stroma", celltype_de_edited_mac_2$contrast)


celltype_de_edited_mac = rbind(celltype_de_edited_mac_1,celltype_de_edited_mac_2)

DEG_geomx_tcells = read.csv("C:/Users/Sahas/Downloads/Masters_Thesis/Ligand-receptor/MultiNichnetR/DEGs_calculated_by_Iga_batch1/dge_within_slide_Segment_bin_FALSE__/dge_deconv_Tcells_dge_within_slide_Segment_bin_FALSE__.csv")

celltype_de_edited_tcells_1 <- data.frame(
  gene = DEG_geomx_tcells $Gene,
  cluster_id = rep("Tcells", nrow(DEG_geomx_tcells )),
  logFC = DEG_geomx_tcells $Estimate,
  p_val = DEG_geomx_tcells $Pr...t..,
  p_adj = DEG_geomx_tcells $FDR,
  contrast = rep("stroma-tumor", nrow(DEG_geomx_tcells))
)


celltype_de_edited_tcells_2 = celltype_de_edited_tcells_1
celltype_de_edited_tcells_2$logFC = -celltype_de_edited_tcells_2$logFC
celltype_de_edited_tcells_2$contrast = gsub("stroma-tumor", "tumor-stroma", celltype_de_edited_tcells_2$contrast)

celltype_de_edited_tcells = rbind(celltype_de_edited_tcells_1,celltype_de_edited_tcells_2)

celltype_de_combined = rbind(celltype_de_edited_mac,celltype_de_edited_tcells)

```


```{r}

# empirical_pval = FALSE
# 
# if(empirical_pval == TRUE){
#   DE_info_emp = get_empirical_pvals(celltype_de_combined)
#   celltype_de = DE_info_emp$de_output_tidy_emp %>% select(-p_val, -p_adj) %>% 
#     rename(p_val = p_emp, p_adj = p_adj_emp)
#   #saveRDS(celltype_de, file = paste0(output_dir,"celltype_de_emp.RDS"))
# } else {
#   celltype_de = celltype_de_combined
#   #saveRDS(celltype_de, file = paste0(output_dir,"celltype_de.RDS"))
# } 


sender_receiver_de = multinichenetr::combine_sender_receiver_de(
  sender_de = celltype_de_combined,
  receiver_de = celltype_de_combined,
  senders_oi = senders_oi,
  receivers_oi = receivers_oi,
  lr_network = lr_network
)


saveRDS(sender_receiver_de, paste0(output_dir,"sender_receiver_de.RDS"))
```



```{r}

logFC_threshold = 0.5 # 0.5
p_val_threshold = 0.05 # 0.05
p_val_adj = TRUE # TRUE 

top_n_target = 250 #250
verbose = TRUE
cores_system = 2


n.cores = min(cores_system, celltype_de_combined$cluster_id %>% unique() %>% length()) 


ligand_activities_targets_DEgenes = suppressMessages(suppressWarnings(
  get_ligand_activities_targets_DEgenes(
    receiver_de = celltype_de_combined,
    receivers_oi = intersect(receivers_oi, celltype_de_combined$cluster_id %>% unique()),
    ligand_target_matrix = ligand_target_matrix,
    logFC_threshold = logFC_threshold,
    p_val_threshold = p_val_threshold,
    p_val_adj = p_val_adj,
    top_n_target = top_n_target,
    verbose = verbose, 
    n.cores = n.cores

  )
))

saveRDS(ligand_activities_targets_DEgenes, paste0(output_dir,"ligand_activities_targets_DEgenes.RDS"))

```


```{r}
ligand_activity_down = FALSE

# Set contrasts
contrasts_oi <- c("'stroma-tumor','tumor-stroma'")

# Create a contrast table
contrast_tbl <- tibble(contrast = c("stroma-tumor","tumor-stroma"), 
                       group = c("stroma", "tumor")) 

sender_receiver_tbl = sender_receiver_de %>% distinct(sender, receiver)

metadata_combined = SummarizedExperiment::colData(sce) %>% tibble::as_tibble()

if(!is.na(batches)){
  grouping_tbl = metadata_combined[,c(sample_id, group_id, batches)] %>% 
    tibble::as_tibble() %>% distinct()
  colnames(grouping_tbl) = c("sample","group",batches)
} else {
  grouping_tbl = metadata_combined[,c(sample_id, group_id)] %>% 
    tibble::as_tibble() %>% distinct()
  colnames(grouping_tbl) = c("sample","group")
}

prioritization_tables = suppressMessages(multinichenetr::generate_prioritization_tables(
    sender_receiver_info = abundance_expression_info$sender_receiver_info,
    sender_receiver_de = sender_receiver_de,
    ligand_activities_targets_DEgenes = ligand_activities_targets_DEgenes,
    contrast_tbl = contrast_tbl,
    sender_receiver_tbl = sender_receiver_tbl,
    grouping_tbl = grouping_tbl,
    scenario = "regular", # all prioritization criteria will be weighted equally
    fraction_cutoff = fraction_cutoff, 
    abundance_data_receiver = abundance_expression_info$abundance_data_receiver,
    abundance_data_sender = abundance_expression_info$abundance_data_sender,
    ligand_activity_down = ligand_activity_down
  ))


saveRDS(prioritization_tables, paste0(output_dir,"prioritization_tables.RDS"))
```



###################### Visualization: Bubble plots disintergrated ################

```{r}
group_oi = "stroma"

#prioritized_tbl_oi_all <- get_top_n_lr_pairs(prioritization_tables, 50, rank_per_group = TRUE)

# prioritized_tbl_oi = prioritized_tbl_oi_all %>% 
#   filter(group == group_oi)

prioritized_tbl_oi = get_top_n_lr_pairs(
  prioritization_tables, 
  50, 
  groups_oi = group_oi, 
  receivers_oi = "Tcells",
  senders_oi = "Macrophages")


# ligand-receptor pseudobulk product expression panel
sample_data = prioritization_tables$sample_prioritization_tbl %>% 
  dplyr::filter(id %in% prioritized_tbl_oi$id) %>% 
  dplyr::mutate(
    sender_receiver = paste(sender, receiver, sep = " --> "), 
    lr_interaction = paste(ligand, receptor, sep = " - ")) %>%
  dplyr::arrange(receiver) %>% 
  dplyr::group_by(receiver) %>%  
  dplyr::arrange(sender, .by_group = TRUE)

sample_data = sample_data %>% 
  dplyr::mutate(sender_receiver = factor(
    sender_receiver, 
    levels = sample_data$sender_receiver %>% unique()
    ))
  
keep_sender_receiver_values = c(0.25, 0.9, 1.75, 4)
names(keep_sender_receiver_values) = levels(sample_data$keep_sender_receiver)
  
p1 = sample_data %>%
    ggplot(aes(sample, lr_interaction, color = scaled_LR_pb_prod, size = keep_sender_receiver)) +
    geom_point() +
    facet_grid(sender_receiver~group, scales = "free", space = "free", switch = "y") +
    scale_x_discrete(position = "top") +
    theme_light() +
    theme(
      axis.ticks = element_blank(),
      axis.title = element_blank(),
      axis.text.y = element_text(face = "bold.italic", size = 9),
      axis.text.x = element_text(size = 9,  angle = 90,hjust = 0),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.spacing.x = unit(0.40, "lines"),
      panel.spacing.y = unit(0.25, "lines"),
      strip.text.x.top = element_text(size = 10, color = "black", face = "bold", angle = 0),
      strip.text.y.left = element_text(size = 9, color = "black", face = "bold", angle = 0),
      strip.background = element_rect(color="darkgrey", fill="whitesmoke", size=1.5, linetype="solid")
    ) + labs(color = "Scaled L-R\npseudobulk exprs product", size= "Sufficient presence\nof sender & receiver") + 
    scale_size_manual(values = keep_sender_receiver_values)

max_lfc = abs(sample_data$scaled_LR_pb_prod) %>% max()

custom_scale_fill = scale_color_gradientn(
  colours = RColorBrewer::brewer.pal(n = 7, name = "RdBu") %>% rev(),
  values = c(0, 0.350, 0.4850, 0.5, 0.5150, 0.65, 1),  
  limits = c(-1*max_lfc, max_lfc))
  
p1 = p1 + custom_scale_fill



pdf(file = paste0(output_dir,"bubble_plot_",group_oi,".pdf"), width = 17, height = 10)
p1
dev.off()
```

```{r}
group_data = prioritization_tables$group_prioritization_table_source  %>% 
    dplyr::mutate(
      sender_receiver = paste(sender, receiver, sep = " --> "), 
      lr_interaction = paste(ligand, receptor, sep = " - "))  %>% 
    dplyr::distinct(id, sender, receiver, sender_receiver, ligand, receptor, lr_interaction, group, activity_scaled, direction_regulation, prioritization_score) %>% 
  dplyr::filter(id %in% sample_data$id) %>% 
  dplyr::arrange(receiver) %>% 
  dplyr::group_by(receiver) %>% 
  dplyr::arrange(sender, .by_group = TRUE)

  group_data = group_data %>% dplyr::mutate(
    sender_receiver = factor(
      sender_receiver, 
      levels = group_data$sender_receiver %>% unique()
      ))
```



```{r}


group_data_olink = 
  inner_join(
    
    group_data %>% 
      left_join(
        celltype_de_combined %>% filter(contrast == "stroma-tumor") %>% 
          select(gene, cluster_id, logFC) %>% 
          dplyr::rename(ligand = gene, `ligand ` = logFC)
        ) %>% 
      left_join(
        celltype_de_combined %>% filter(contrast == "stroma-tumor") %>% 
          select(gene, cluster_id, logFC) %>% 
          dplyr::rename(receptor = gene, `receptor ` = logFC)
        ) %>% 
      tidyr::gather(LR, logFC,`ligand `:`receptor `),
    
    group_data %>% 
      left_join(
        celltype_de_combined %>% filter(contrast == "stroma-tumor") %>% 
          select(gene, cluster_id, p_adj) %>% 
          dplyr::rename(ligand = gene, `ligand ` = p_adj)
        ) %>% 
      left_join(
        celltype_de_combined %>% filter(contrast == "stroma-tumor") %>% 
          select(gene, cluster_id, p_adj) %>% 
          dplyr::rename(receptor = gene, `receptor ` = p_adj)
        ) %>% 
      tidyr::gather(LR, pval,`ligand `:`receptor `) %>% mutate(neg_log_pval = -log10(pval))
    
  )
  
#group_data_olink = group_data_olink %>% mutate(olink_type = "Diorio")
  
p_olink = group_data_olink %>% 
    ggplot(aes(LR , lr_interaction, color = logFC, size = neg_log_pval)) +
    geom_point() +
    facet_grid(sender_receiver ~ cluster_id, scales = "free", space = "free", switch = "y") +
    scale_x_discrete(position = "top") +
    theme_light() +
    theme(
      axis.ticks = element_blank(),
      axis.title = element_blank(),
      axis.title.y = element_blank(),
      #axis.text.y = element_blank(),
      axis.text.y = element_text(face = "bold.italic", size = 9),
      axis.text.x = element_text(size = 9,  angle = 90,hjust = 0),
      strip.text.x.top = element_text(angle = 0),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.spacing.x = unit(0.20, "lines"),
      panel.spacing.y = unit(0.25, "lines"),
      strip.text.x = element_text(size = 10, color = "black", face = "bold"),
      #strip.text.y.left = element_text(size = 9, color = "black", face = "bold", angle = 0),
      strip.text.y = element_blank(),
      strip.background = element_rect(color="darkgrey", fill="whitesmoke", size=1.5, linetype="solid")
    ) + labs(color = "LogFC stroma-vs-tumor") + labs(size = "-log10(pval)")
  max_lfc = abs(group_data_olink$logFC) %>% max(na.rm = TRUE)
  custom_scale_fill = scale_color_gradientn(
    colours = RColorBrewer::brewer.pal(n = 7, name = "RdBu") %>% rev(),
    values = c(0, 0.30, 0.40, 0.5, 0.60, 0.70, 1), 
    limits = c(-1*max_lfc, max_lfc))
  
p_olink = p_olink + custom_scale_fill + scale_size_binned_area(max_size = 4)


pdf(file = paste0(output_dir,"LogFC_and_Pval_",group_oi,".pdf"), width = 17, height = 10)
p_olink
dev.off()

```


```{r}
p = patchwork::wrap_plots(
      p1,p_olink,
      nrow = 1,guides = "collect",
      widths = c(sample_data$sample %>% unique() %>% length(), 2*length(unique(celltype_de_combined$cluster_id)))
)


pdf(file = paste0(output_dir,"combined_plot_",group_oi,".pdf"), width = 17, height = 10)
p
dev.off()

```


###################### Visualization ################


### # Create circos plots

```{r circos plots}


prioritized_tbl_oi_all <- get_top_n_lr_pairs(prioritization_tables, 50, rank_per_group = TRUE)

prioritized_tbl_oi <- prioritization_tables$group_prioritization_tbl %>%
  filter(id %in% prioritized_tbl_oi_all$id) %>%
  distinct(id, sender, receiver, ligand, receptor, group) %>% left_join(prioritized_tbl_oi_all)

# Set NA values to zero
prioritized_tbl_oi$prioritization_score[is.na(prioritized_tbl_oi$prioritization_score)] <- 0

# Define sender and receiver cells
senders_receivers <- union(prioritized_tbl_oi$sender %>% unique(), prioritized_tbl_oi$receiver %>% unique()) %>% sort()

# Set colors for sender and receiver cells
colors_sender <- RColorBrewer::brewer.pal(n = length(senders_receivers), name = 'Spectral') %>% magrittr::set_names(senders_receivers)
colors_receiver <- RColorBrewer::brewer.pal(n = length(senders_receivers), name = 'Spectral') %>% magrittr::set_names(senders_receivers)

# Create circos plots to visualize top 50 predictions across all contrasts, senders, and receivers of interest
circos_list <- make_circos_group_comparison(prioritized_tbl_oi, colors_sender, colors_receiver)


pdf(file = paste0(output_dir,"circos_plot_stroma.pdf"), width = 10, height = 10)
circos_list$stroma
dev.off()

pdf(file = paste0(output_dir,"circos_plot_tumor.pdf"), width = 10, height = 10)
circos_list$tumor
dev.off()

pdf(file = paste0(output_dir,"circos_plot_legend.pdf"), width = 10, height = 10)
circos_list$legend
dev.off()
```



########### Generating bubble plots

```{r bubble plots , width = 10, height = 10}
group_oi = "stroma"

prioritized_tbl_oi_M_50 = prioritized_tbl_oi_all %>% 
  filter(group == group_oi)

plot1 = make_sample_lr_prod_activity_plots_Omnipath(
  prioritization_tables, 
  prioritized_tbl_oi_M_50 %>% inner_join(lr_network_all)
  )


pdf(file = paste0(output_dir,"bubble_plot_",group_oi,".pdf"), width = 17, height = 10)
plot1
dev.off()

prioritized_tbl_oi_M_50 = get_top_n_lr_pairs(
  prioritization_tables, 
  50, 
  groups_oi = group_oi, 
  receivers_oi = "Tcells",
  senders_oi = "Macrophages")

plot2 = make_sample_lr_prod_activity_plots_Omnipath(
  prioritization_tables, 
  prioritized_tbl_oi_M_50 %>% inner_join(lr_network_all))

pdf(file = paste0(output_dir,"bubble_plot_Macrophages_to_Tcells",group_oi,".pdf"), width = 17, height = 10)
plot2
dev.off()




prioritized_tbl_oi_M_50 = get_top_n_lr_pairs(
  prioritization_tables, 
  50, 
  groups_oi = group_oi, 
  receivers_oi = "Macrophages",
  senders_oi = "Tcells")

plot3 = make_sample_lr_prod_activity_plots_Omnipath(
  prioritization_tables, 
  prioritized_tbl_oi_M_50 %>% inner_join(lr_network_all))
pdf(file = paste0(output_dir,"bubble_plot_Tcells_to_Macrophages",group_oi,".pdf"), width = 17, height = 10)
plot3
dev.off()


```


```{r}
group_oi = "tumor"

prioritized_tbl_oi_M_50 = prioritized_tbl_oi_all %>% 
  filter(group == group_oi)

plot4 = make_sample_lr_prod_activity_plots_Omnipath(
  prioritization_tables, 
  prioritized_tbl_oi_M_50 %>% inner_join(lr_network_all)
  )



pdf(file = paste0(output_dir,"bubble_plot_",group_oi,".pdf"), width = 17, height = 10)
plot4
dev.off()


prioritized_tbl_oi_M_50 = get_top_n_lr_pairs(
  prioritization_tables, 
  50, 
  groups_oi = group_oi, 
  receivers_oi = "Tcells",
  senders_oi = "Macrophages")

plot5 = make_sample_lr_prod_activity_plots_Omnipath(
  prioritization_tables, 
  prioritized_tbl_oi_M_50 %>% inner_join(lr_network_all))

pdf(file = paste0(output_dir,"bubble_plot_Macrophages_to_Tcells",group_oi,".pdf"), width = 17, height = 10)
plot5
dev.off()




prioritized_tbl_oi_M_50 = get_top_n_lr_pairs(
  prioritization_tables, 
  50, 
  groups_oi = group_oi, 
  receivers_oi = "Macrophages",
  senders_oi = "Tcells")

plot6 = make_sample_lr_prod_activity_plots_Omnipath(
  prioritization_tables, 
  prioritized_tbl_oi_M_50 %>% inner_join(lr_network_all))
pdf(file = paste0(output_dir,"bubble_plot_Tcells_to_Macrophages",group_oi,".pdf"), width = 17, height = 10)
plot6
dev.off()

```


