---
title: "Ligand Receptor Prediction: Nichenetr"
author: "Gayani GImhani Anandagoda"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r libraries}
library("ggplot2")
library(gridExtra)
library(nichenetr)
#library(Seurat)
#library(SeuratObject)
library(tidyverse)
library(DESeq2)
library(dplyr)
```


######################## to be cleaned ########################################

```{r}
sender_cell = "Tcells" # check the possibility to use c("Tcells","Macrophages")

Receiver_cell = "Macrophages"

FDR_threshold = 0.05

contrast = NULL # "negCD8_negIBA1 - posCD8_posIBA1" 

cell_type_keep = "negCD8_negIBA1"

data_group = "tumor"

Up_regulated = FALSE

fold_change_cutoff = 0.05


```

```{r}

#input_dir = "C:/Users/Sahas/Downloads/Masters_Thesis/Data/Batch01/"

output_dir = "C:/Users/Sahas/Downloads/Masters_Thesis/Ligand-receptor/NichNet/batch1_output/cellchat_receptors_as_geneset_of_interest/tcells-macrophages/"

#folder_name <- gsub(" ", "", contrast)
#folder_name <- gsub("-", "vs", folder_name) 

folder_name <- cell_type_keep

if (!dir.exists(paste0(output_dir,folder_name))) {
  new_dir = paste0(output_dir,folder_name)
  dir.create(new_dir,recursive = TRUE)
  message("Directory created")
  output_dir = new_dir
} else {
  output_dir = paste0(output_dir,folder_name)
}

```

```{r input data}
meta = readRDS("C:/Users/Sahas/Downloads/Masters_Thesis/Ligand-receptor/MultiNichnetR/meta.RDS")

keep = rownames(meta[meta$Segment == data_group & meta$Annotation == cell_type_keep,])

deconv_ct_list_filtered = readRDS("C:/Users/Sahas/Downloads/Masters_Thesis/Ligand-receptor/NichNet/batch1_output/Nichenet_obj_processed/bp_res_mid_lvl_ct_45_filtered_deconv_ct_list_cf_0.01.RDS")

DEG_geomx_1 = read.csv("C:/Users/Sahas/Downloads/Masters_Thesis/Data/Batch01/DGE_pre_post_merged/dge_deconv_Macrophages_dge_within_slide_Annotation_cell_bin_FALSE__Segment.csv")

potential_ligands = NULL

geneset_oi = NULL

```

```{r loadind the model}

dir_name = "C:/Users/Sahas/Downloads/Masters_Thesis/Ligand-receptor/NichNet/Nichenet_Model/" # replace with the url at the end

lr_network = readRDS(paste0(dir_name,"lr_network_human_21122021.rds"))

ligand_target_matrix = readRDS(paste0(dir_name,"ligand_target_matrix_nsga2r_final.rds"))

weighted_networks = readRDS(paste0(dir_name,"weighted_networks_nsga2r_final.rds"))

lr_network <- lr_network %>% distinct(from, to)

```

# LR Analysis 

```{r defining potential_ligands}

Sender_cell_expr = deconv_ct_list_filtered[[sender_cell]]

colnames(Sender_cell_expr) <- gsub('\\.dcc', paste0('_', sender_cell), colnames(Sender_cell_expr))

Sender_cell_expr = Sender_cell_expr[, colnames(Sender_cell_expr) %in% keep]

Receiver_cell_expr = deconv_ct_list_filtered[[Receiver_cell]]

colnames(Receiver_cell_expr) <- gsub('\\.dcc', paste0('_', Receiver_cell), colnames(Receiver_cell_expr))

Receiver_cell_expr = Receiver_cell_expr[, colnames(Receiver_cell_expr) %in% keep]
  
rownames(Sender_cell_expr) <- convert_alias_to_symbols(rownames(Sender_cell_expr), "human", verbose = FALSE)

rownames(Receiver_cell_expr) <- convert_alias_to_symbols(rownames(Receiver_cell_expr), "human", verbose = FALSE)

ligands <- lr_network %>% pull(from) %>% unique()
expressed_ligands <- intersect(ligands,rownames(Sender_cell_expr))

receptors <- lr_network %>% pull(to) %>% unique()
expressed_receptors <- intersect(receptors,rownames(Receiver_cell_expr))

potential_ligands <-  lr_network %>% filter(from %in% expressed_ligands & to %in% expressed_receptors) %>% 
  pull(from) %>% unique()

```


```{r background genes}

# background_expressed_genes comes from the receiver

background_expressed_genes <- rownames(Receiver_cell_expr) %>% .[. %in% rownames(ligand_target_matrix)]
```

# 1. Gene set of interests: Differentially expressed genes

```{r change colnames of DEG dataframes}
DEG_geomx = DEG_geomx_1

colnames(DEG_geomx)[colnames(DEG_geomx) == "Pr...t.."] <- "prob" # change the colname
#colnames(DEG_geomx)[colnames(DEG_geomx) == "data_group"] <- "Data_group" # change the colname
```

```{r gene set of interest, eval=FALSE}

#DEG_geomx = DEG_geomx %>% filter(Data_group == data_group & Contrast == contrast) %>% filter(FDR < FDR_threshold) 

DEG_geomx = DEG_geomx %>% filter(Contrast == contrast) %>% filter(FDR < FDR_threshold) 

if(Up_regulated == TRUE){
  
  DEG_geomx = DEG_geomx %>% filter(Estimate > fold_change_cutoff) 
  
} else{
  
  DEG_geomx <- DEG_geomx %>% filter(abs(Estimate) > fold_change_cutoff)
}

gene = DEG_geomx$Gene

geneset_oi <- gene %>% .[. %in% rownames(ligand_target_matrix)] 

intersect(geneset_oi,background_expressed_genes)

intersect(geneset_oi,potential_ligands)

```


```{r to be deleted}

# gene set of interest from cellchat receptors

cellchat_obj = readRDS("C:/Users/Sahas/Downloads/Masters_Thesis/Ligand-receptor/CellChat/ouput_batch1/output_0.01_CD8_IBA1_annotations/LRpairs_Tcells_Macrophages_0.01__negCD8_negIBA1_stroma.RDS")

cellchat_obj = cellchat_obj %>% filter(source == sender_cell, target == Receiver_cell)

geneset_oi = unique(cellchat_obj$receptor)

expressed_ligands = unique(cellchat_obj$ligand)

expressed_receptors = unique(cellchat_obj$receptor)

potential_ligands <-  lr_network %>% filter(from %in% expressed_ligands & to %in% expressed_receptors) %>% 
  pull(from) %>% unique()

 
```


# predicting ligand activity

```{r predicting ligand activity}
ligand_activities <- predict_ligand_activities(geneset = geneset_oi,
                                               background_expressed_genes = background_expressed_genes,
                                               ligand_target_matrix = ligand_target_matrix,
                                               potential_ligands = potential_ligands)



```

```{r}


ligand_activities <- ligand_activities %>% arrange(-aupr_corrected)

ligand_activities_Nichener_obj = setNames(list(ligand_activities,geneset_oi),list("ligand_activities","geneset_oi"))


saveRDS(ligand_activities_Nichener_obj, file = paste0(output_dir,"/LR_activities_Nichener_obj_",data_group,"_",".RDS"))

```

