---
title: "Nichenet_plotting"
author: "Gayani GImhani Anandagoda"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library("ggplot2")
library(gridExtra)
library(nichenetr)
#library(Seurat)
#library(SeuratObject)
library(tidyverse)
library(DESeq2)
library(dplyr)
```


```{r}
aupr_corrected_cutoff = 0.01

top_n_ligands = 30 # top 30 ligands

top_n_targets = 500 # top 200 targets

weight_quantile_cutoff = 0.25 # weight quantile cutoff
```


```{r}
################# move to the visualization plot ###############

#input_dir = "C:/Users/Sahas/Downloads/Masters_Thesis/Data/Batch01/"

output_dir = "C:/Users/Sahas/Downloads/Masters_Thesis/Ligand-receptor/NichNet/batch1_output/cellchat_receptors_as_geneset_of_interest/tcells-macrophages/negCD8_negIBA1/"

```

```{r}
ligand_activities_Nichener_obj = readRDS( paste0(output_dir,"LR_activities_Nichener_obj_tumor_.RDS"))

dir_name = "C:/Users/Sahas/Downloads/Masters_Thesis/Ligand-receptor/NichNet/Nichenet_Model/" # replace with the url at the end

ligand_target_matrix = readRDS(paste0(dir_name,"ligand_target_matrix_nsga2r_final.rds"))

```

######################## visualization plot ####################


```{r, fig.width=15, fig.height=6}



ligand_activities = ligand_activities_Nichener_obj$ligand_activities

geneset_oi = ligand_activities_Nichener_obj$geneset_oi


best_upstream_ligands <- ligand_activities %>% top_n(top_n_ligands, aupr_corrected) %>% # top 30 ligands
  arrange(-aupr_corrected) %>% pull(test_ligand)

#best_upstream_ligands <- ligand_activities %>% filter(aupr_corrected > aupr_corrected_cutoff) %>% 
#  arrange(-aupr_corrected) %>% pull(test_ligand)

#best_upstream_ligands = ligand_activities[grep("HLA",ligand_activities$test_ligand),]$test_ligand

active_ligand_target_links_df <- best_upstream_ligands %>%
  lapply(get_weighted_ligand_target_links,
         geneset = geneset_oi,
         ligand_target_matrix = ligand_target_matrix,
         n = top_n_targets) %>% bind_rows() # top 200 targets

# saveRDS(active_ligand_target_links_df, file = paste0(output_dir,"Lactive_ligand_target_links_df_norm_threshold_0.RDS"))

active_ligand_target_links_df = na.omit(active_ligand_target_links_df)

active_ligand_target_links <- prepare_ligand_target_visualization(
  ligand_target_df = active_ligand_target_links_df,
  ligand_target_matrix = ligand_target_matrix,
  cutoff = weight_quantile_cutoff) # weight quantile cutoff

```

```{r}
order_ligands <- intersect(best_upstream_ligands, colnames(active_ligand_target_links)) %>% rev() # rev reverse the order

order_targets <- active_ligand_target_links_df$target %>% unique() %>% intersect(rownames(active_ligand_target_links))

vis_ligand_target <- t(active_ligand_target_links[order_targets,order_ligands])

p_ligand_target_network <- make_heatmap_ggplot(vis_ligand_target, "Prioritized macrophage ligands", "genes in T Cell",
                    color = "purple", legend_title = "Regulatory potential") +
  scale_fill_gradient2(low = "whitesmoke",  high = "purple")+
  ggtitle("Macrophage - T Cell \n (Gene set of Interest = receptors and ligands from cellchat")


p_ligand_target_network <- p_ligand_target_network +
  theme(plot.title = element_text(hjust = 0.5, face = "bold", size = 14))


pdf(file.path(output_dir, "heatmap.pdf"), width = 10, height = 6)

p_ligand_target_network

dev.off()

print("Plots saved")
```


```{r cell type abundance plot ,eval=FALSE}

df_grouped_samples = meta %>% group_by(Segment,NACT_status,Annotation,labels) %>% summarise(count = n())

pdf(file.path(output_dir, "cell_type_abundance.pdf"), width = 10, height = 6)

ggplot(df_grouped_samples, aes(x = Annotation, y = count, fill = labels)) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_grid(Segment ~ NACT_status) + 
  theme_minimal() +
  geom_hline(yintercept = 10, linetype = "solid", color = "black") +
  #scale_x_discrete(position = "top") +
  #labs(title = "Cell Label Counts by Segment and NACT Status",
       #x = "Annotation_cell",
       #y = "Count") +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 0.5),
    strip.text.y = element_text(angle = 0)  # <- makes facet labels horizontal
  )


plot1 = ggplot(df_grouped_samples, aes(x = Annotation, y = count, fill = labels)) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_grid(. ~ Segment ) + 
  theme_minimal() +
  geom_hline(yintercept = 10, linetype = "solid", color = "black") +
  #labs(title = "Cell Label Counts by Segment and NACT Status",
       #x = "Annotation_cell",
       #y = "Count") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


plot2 = ggplot(df_grouped_samples, aes(x = Annotation, y = count, fill = labels)) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_grid(. ~ NACT_status) + 
  theme_minimal() +
  geom_hline(yintercept = 10, linetype = "solid", color = "black") +
  #labs(title = "Cell Label Counts by Segment and NACT Status",
       #x = "Annotation_cell",
      # y = "Count") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


plot3 = ggplot(df_grouped_samples, aes(x = NACT_status, y = count, fill = labels)) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_grid(. ~ Segment) + 
  theme_minimal() +
  geom_hline(yintercept = 10, linetype = "solid", color = "black") +
  #labs(title = "Cell Label Counts by Segment and NACT Status",
       #x = "Annotation_cell",
      # y = "Count") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

grid.arrange(plot1, plot2, plot3, ncol = 2)

dev.off()
print("Plots saved to density_plots.pdf")
```

